server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: customer_service_route
        predicates:
        - Path=/customer-service/**
        filters:
        - RewritePath=/customer-service/(?<segment>.*), /$\{segment}
        uri: http://localhost:8082